server :
   port : 9001  
   
spring:
  application:
    name: CONFIG-SERVER

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#       defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rahul70908/config-server
          clone-on-start: true
       
