server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DepartmentMicroService
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
        hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
  application:
    name: USER-SERVICE       
    
#   Added in Config Server
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      
#  instance:
#    hostname: localhost

#Actuator Configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      DEPARTMENT-SERVICE : 
         registerHealthIndicator : true    
         eventConsumerBufferSize : 10
         failureRateThreshold : 50
         minimumNumberOfCalls : 5
         automaticTransitionFromOpenToHalfOpenEnabled : true
         waitDurationInOpenState : 5s
         permittedNumberOfCallsInHalfOpenState : 3
         slidingWindowSize : 10
         slidingWindowType : COUNT_BASED
      
  retry:
    instances:
      DEPARTMENT-SERVICE:
        max-attempts: 5
        wait-duration: 10s     
         
  ratelimiter:
    instances:
      DEPARTMENT-SERVICE:
        register-health-indicator:  false
        limit-for-period: 10
        limit-refresh-period: 10s
        timeout-duration: 3s
           
        