server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DepartmentMicroService
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
        hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        
  application:
    name: DEPARTMENT-SERVICE

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/    
#    
#  instance:
#    hostname: localhost
    
    